### ISSUE TITLE
Need help installing Libximc on a ubuntu 20.04 computer

### ISSUE THREAD

**Issue by georgeExotic** [EPC-MSU/libximc#13]
Hello guys, 

I have been trying to install this library on my ubuntu 20.04 installation. I plan to use some python3 code to control a Standa 	8MRB450-350-60 - Large Aperture Rotary Table via 8SMC5-USB - Stepper & DC Motor Controller. 

I have tried installing via pip but the library does not work as expected. I tried the following:

sudo apt-get update
sudo apt-get install build-essential make cmake curl git autotools-dev automake autoconf libtool doxygen bison flex debhelper lintian texlive texlive-latex-extra texlive-fonts-extra texlive-lang-cyrillic default-jre-headless default-jdk  pkg-config check dh-autoreconf  libfl-dev lsb-release python3 python3-pip
sudo apt-get install ruby
sudo apt-get install autoconf automake libtool
git clone https://github.com/EPC-MSU/libximc.git
cd libximc
sudo apt-get install libfl-dev
sudo apt-get install bison
./build.sh libdeb

This takes a while and eventually fails like this.

make[5]: Entering directory '/home/tti/libximc/wrappers/java/src/c'
../../../../xigen/src/xigen --gen-jni -w -x ../../../../version -i ../../../../libximc/src/protocol.xi -o ../../../../wrappers/java/src/c/ru_ximc_libximc_JXimc-gen.c -t ./ru_ximc_libximc_JXimc-template.c
Inline command firmware_version is replaced with non-inline
Inline command firmware_version is replaced with non-inline
Inline command bootloader_version is replaced with non-inline
Inline command bootloader_version is replaced with non-inline
JNI library generated by xigen  /home/tti/libximc/wrappers/java/src/c
make  all-am
make[6]: Entering directory '/home/tti/libximc/wrappers/java/src/c'
/bin/bash ../../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../..  -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux -I../../../../wrappers/java/gen -I../../../../libximc/include -I/home/tti/libximc/deps/xiwrapper -I/home/tti/libximc/deps/miniupnpc/include  -Wno-deprecated-declarations -Wall -Werror -Wextra -Wshadow -Wno-switch -MT libjximc_la-ru_ximc_libximc_JXimc.lo -MD -MP -MF .deps/libjximc_la-ru_ximc_libximc_JXimc.Tpo -c -o libjximc_la-ru_ximc_libximc_JXimc.lo `test -f 'ru_ximc_libximc_JXimc.c' || echo './'`ru_ximc_libximc_JXimc.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../.. -I/usr/lib/jvm/java-11-openjdk-amd64/include -I/usr/lib/jvm/java-11-openjdk-amd64/include/linux -I../../../../wrappers/java/gen -I../../../../libximc/include -I/home/tti/libximc/deps/xiwrapper -I/home/tti/libximc/deps/miniupnpc/include -Wno-deprecated-declarations -Wall -Werror -Wextra -Wshadow -Wno-switch -MT libjximc_la-ru_ximc_libximc_JXimc.lo -MD -MP -MF .deps/libjximc_la-ru_ximc_libximc_JXimc.Tpo -c ru_ximc_libximc_JXimc.c  -fPIC -DPIC -o .libs/libjximc_la-ru_ximc_libximc_JXimc.o
In file included from ru_ximc_libximc_JXimc.c:1:
ru_ximc_libximc_JXimc-gen.c:1:10: fatal error: ru_ximc_libximc_JXimc.h: No such file or directory
    1 | #include "ru_ximc_libximc_JXimc.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[6]: *** [Makefile:524: libjximc_la-ru_ximc_libximc_JXimc.lo] Error 1
make[6]: Leaving directory '/home/tti/libximc/wrappers/java/src/c'
make[5]: *** [Makefile:416: all] Error 2
make[5]: Leaving directory '/home/tti/libximc/wrappers/java/src/c'
make[4]: *** [Makefile:429: all-recursive] Error 1
make[4]: Leaving directory '/home/tti/libximc/wrappers/java/src'
make[3]: *** [Makefile:429: all-recursive] Error 1
make[3]: Leaving directory '/home/tti/libximc/wrappers/java'
make[2]: *** [Makefile:429: all-recursive] Error 1
make[2]: Leaving directory '/home/tti/libximc/wrappers'
make[1]: *** [Makefile:485: all-recursive] Error 1
make[1]: Leaving directory '/home/tti/libximc'
make: *** [Makefile:417: all] Error 2

I would appreciate if someone could help me install it successfully and help me implement some python3 code.

**Comment by Zapunidi** [comment]
Hi, [georgeExotic](https://github.com/georgeExotic).
Let's establish the basics first. If you want to use python3 with libximc, then we just recently published a wonderful tidy libximc package on PyPI. `pip install libximc` must work on Ubuntu 20.04 and many other Linuxes. Just see how it works on a Google colab virtual machine: https://colab.research.google.com/drive/1tGHFRcVwf0DmQOFm_JtOOr7fXsfKUSrg
Use Runtime->Run all to see that the code works. Then just do the same on your machine. I strongly encourage you to use this option.
You may want to do force reinstall the pip package to get the latest version `pip install --force-reinstall libximc`. The previous one was deployed for test purposes mostly.
Other working option to install libximc is to download programming package from the official website: https://files.xisupport.com/Software.en.html Then follow instructions from readme files and programming manual. Not recommended. Old python bindings there are.
And building libximc from source is not an option at all, because it is for those who want to change libximc for their own specific usages.

**Comment by Zapunidi** [comment]
I believe that the issue is closed.
